9776mk/final_pjt

articles/templates/articles/home.html, articles/views.py, final_pjt/urls.py, templates/base.html
=> feat: navbar 생성

templates/base.html
=> style: navbar 수정

articles/templates/articles/index.html, templates/base.html
=> etc: navbar url 연결

static/css/base.css, templates/base.html
=> etc: navbar 수정

articles/templates/articles/index.html, static/css/base.css, templates/base.html
=> style: 게시판, navbar 수정

articles/templates/articles/index.html, static/css/base.css, templates/base.html
=> nav 조금 게시판 조금 수정

articles/templates/articles/index.html, static/css/base.css, static/css/board.css
게시판 수정 및 css 분리 + 게시판 배경 이미지 추가
=> style: 게시판 수정 및 css 분리

templates/base.html
=> etc: navbar user image 오류 수정

templates/base.html
=> etc: navbar 수정 - 메뉴랑 사용자

articles/views.py
home 계산식에서 ZeroDivisionError 발생 fix 함
=> fix: home - 계산식 ZeroDivisionError fix

accounts/templates/accounts/guestbook.html, accounts/views.py, static/js/accounts_gb_article_async.js, static/js/accounts_gb_comment_async.js
1. 비밀글 체크 버튼 디자인 수정 후 각 댓글 및 비동기 코드에 적용해야 함.
2. 비밀글 배경색 수정 후 각 댓글 및 비동기 코드에 적용해야 함.
=> fix(accounts): 방명록 비밀글 비동기 수정 + 자물쇠 아이콘 추가

articles/templates/articles/create.html, articles/templates/articles/detail.html, scss/board_detail.scss, static/css/board_detail.css
=> etc: 게시판 create 이미지폼 수정

templates/base.html
=> style: navbar에  알림창 modal 붙임

articles/templates/articles/index.html, articles/views.py, static/css/board.css
=> style: 게시판 pagination

templates/base.html
=> etc: navbar 스터디 추가

articles/forms.py
=> 개발마당 글 작성 textarea스타일

articles/templates/articles/create.html, articles/templates/articles/detail.html, scss/studies.scss, static/css/studies.css, studies/templates/studies/create.html, studies/templates/studies/detail.html
스터디 create 폼 placeholder 추가, 게시판 create 제목 폼 수정
=> etc: 스터디 create 폼 placeholder 추가, 게시판 create 제목 폼 수정

articles/forms.py, scss/studies.scss, static/css/studies.css, studies/templates/studies/detail.html
=> style: 스터디 detail fe, 반응형

articles/templates/articles/index.html, articles/templates/articles/search.html, articles/urls.py, articles/views.py, scss/studies.scss, static/css/studies.css, studies/templates/studies/detail.html
articles search fe, 스터디 detail 버튼 수정
=> style: articles search fe, 스터디 detail 버튼 수정

articles/templates/articles/home.html, studies/templates/studies/index.html
=> fix: 공부방 빈 이미지 문제 해결

articles/templates/articles/index.html, articles/templates/articles/search.html
=> etc: articles search 말줄임표, 조회수 추가

scss/board.scss
=> etc: scss 파일 호버 부분 빠진거 채움

studies/templates/studies/board_index.html, studies/views.py
=> 스터디 디테일 문제일경우..

scss/board.scss, static/css/board.css, studies/templates/studies/board_index.html, studies/views.py
=> style: 공부방 게시판 index 수정
